const Images = {
    splashScreen: require('./../assets/img/logo.jpg'),
    qqIcon: require('./../assets/img/qq-icon.png'),
    qqIcon_white: require('./../assets/img/qq_Icon_white.png'),
    imageIcon: require('./../assets/img/image_gray_icon.png'),
    verifyCodeIcon: require('./../assets/img/verifycode.png'),
    captchBackground: require('./../assets/img/captcha_background-1.jpg'),
    smsIcon: require('./../assets/img/sms-1-icon.png'),
    lockIIcon: require('./../assets/img/lock-icon.png'),
    handIcon: require('./../assets/img/hand-icon.png'),

    /* Home */
    homeBackTop: require('./../assets/img/home/home_top.png'),
    silcCardIcon: require('./../assets/img/home/silk_card.png'),
    jianzhiqianbao: require('./../assets/img/home/jianzhiqianbao.png'),
    flightLotIcon: require('./../assets/img/home/flignt-lot.png'),
    amoyIcon: require('./../assets/img/home/amoy.png'),
    usersIcon: require('./../assets/img/home/users-icon.png'),
    promotionIcon: require('./../assets/img/home/promotion-icon.png'),
    questionIcon: require('./../assets/img/home/question-icon.png'),
    prizeIcon: require('./../assets/img/home/prize-icon.png'),
    userfavoriteIcon: require('./../assets/img/home/user-favorite.png'),
    wodedingdanIcon: require('./../assets/img/home/wodedingdan.png'),
    footerBackImage: require('./../assets/img/home/home-footer.png'),
    homeIcon: require('./../assets/img/home/home-icon.png'),
    homeIconActive: require('./../assets/img/home/home-icon-active.png'),
    profileIcon: require('./../assets/img/home/profile-icon.png'),
    profileIconActive: require('./../assets/img/home/profile-active-icon.png'),
    preorderIcon: require('./../assets/img/home/pre-order-icon.png'),
    preorderIconActive: require('./../assets/img/home/pre-order-active-icon.png'),
    taskIcon: require('./../assets/img/home/task-icon.png'),
    taskIconActive: require('./../assets/img/home/task-icon-active.png'),
    noticeIcon: require('./../assets/img/home/notice.png'),
    promotion: require('./../assets/img/home/promotion-1.png'),
    prizeStack: require('./../assets/img/home/prizeStack.png'),
    lotoBakcground: require('./../assets/img/home/lotoSplashBack.png'),
    lotoBakcTop: require('./../assets/img/home/lotoSplashBack-top.png'),
    lotoStart: require('./../assets/img/home/loto-start.png'),
    smileFace: require('./../assets/img/home/smile-face.png'),
    mission_01: require('./../assets/img/icons/total-mission_01.png'),
    mission_02: require('./../assets/img/icons/total-mission_02.png'),
    mission_03: require('./../assets/img/icons/total-mission_03.png'),
    mission_04: require('./../assets/img/icons/total-mission_04.png'),
    mission_05: require('./../assets/img/icons/total-mission_05.png'),
    mission_06: require('./../assets/img/icons/total-mission_06.png'),
    mission_07: require('./../assets/img/icons/total-mission_07.png'),
    alarm_clock: require('./../assets/img/icons/alarm-clock.png'),
    gold_stack_plus: require('./../assets/img/icons/gold_stack_plus.png'),
    preorders_01: require('./../assets/img/preorders/preorders_01.png'),
    preorders_02: require('./../assets/img/preorders/preorders_02.png'),
    preorders_03: require('./../assets/img/preorders/preorders_03.png'),
    orange_head: require('./../assets/img/preorders/orange_head.png'),
    product: require('./../assets/img/preorders/product.png'),
    tab_2: require('./../assets/img/preorders/tab-2.png'),
    delivery: require('./../assets/img/preorders/delivery.png'),
    prendig_review: require('./../assets/img/preorders/prendig_review.png'),
    icon_passport: require('./../assets/img/icons/icon_passport.png'),
    icon_qq_number: require('./../assets/img/icons/icon_qq_number.png'),
    icon_jd: require('./../assets/img/icons/icon_JD.png'),
    icon_bankcard: require('./../assets/img/icons/icon_bankcard.png'),

};

export default Images;
