const Images = {
    splashScreen: require('./../assets/img/logo.jpg'),
    qqIcon: require('./../assets/img/qq-icon.png'),
    qqIcon_white: require('./../assets/img/qq_Icon_white.png'),
    imageIcon: require('./../assets/img/image_gray_icon.png'),
    verifyCodeIcon: require('./../assets/img/verifycode.png'),
    captchBackground: require('./../assets/img/captcha_background-1.jpg'),
    smsIcon: require('./../assets/img/sms-1-icon.png'),
    lockIIcon: require('./../assets/img/lock-icon.png'),
    handIcon: require('./../assets/img/hand-icon.png'),

    /* Home */
    homeBackTop: require('./../assets/img/home/home_top.png'),
    silcCardIcon: require('./../assets/img/home/silk_card.png'),
    jianzhiqianbao: require('./../assets/img/home/jianzhiqianbao.png'),
    flightLotIcon: require('./../assets/img/home/flignt-lot.png'),
    amoyIcon: require('./../assets/img/home/amoy.png'),
    usersIcon: require('./../assets/img/home/users-icon.png'),
    promotionIcon: require('./../assets/img/home/promotion-icon.png'),
    questionIcon: require('./../assets/img/home/question-icon.png'),
    prizeIcon: require('./../assets/img/home/prize-icon.png'),
    userfavoriteIcon: require('./../assets/img/home/user-favorite.png'),
    wodedingdanIcon: require('./../assets/img/home/wodedingdan.png'),
    footerBackImage: require('./../assets/img/home/home-footer.png'),
    homeIcon: require('./../assets/img/home/home-icon.png'),
    homeIconActive: require('./../assets/img/home/home-icon-active.png'),
    profileIcon: require('./../assets/img/home/profile-icon.png'),
    profileIconActive: require('./../assets/img/home/profile-active-icon.png'),
    preorderIcon: require('./../assets/img/home/pre-order-icon.png'),
    preorderIconActive: require('./../assets/img/home/pre-order-active-icon.png'),
    taskIcon: require('./../assets/img/home/task-icon.png'),
    taskIconActive: require('./../assets/img/home/task-icon-active.png'),
    noticeIcon: require('./../assets/img/home/notice.png'),
};

export default Images;
